@startuml

' hide the spot
hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

entity "User" {
  id: number <<PK>> <<generated>>
  --
  manager_id: number <<PK>>
  name: string
  phone: string
  email: string
  password_hash: string
}

entity "Employee" {
  id: number <<PK>> <<generated>>
  --
  name: string
  phone: string
  email: string
  password_hash: string
}

entity "EmployeePermission" {
 manager_id: number <<PK>>
 permission_id: number <<PK>>
}

entity "Permission" {
  id: number <<PK>> <<generated>>
  type: string <<PK>>
}

entity "Order" {
  id: number <<PK>> <<generated>>
  user_id: number <<FK>>
  restaurant_id: number <<FK>>
  address: string
  zip_code: string
}

entity "OrderEntry" {
  id: number <<PK>> <<generated>>
  order_id: number <<FK>>
  meal_id: number <<FK>>
  count: number
}

entity "OrderStatus" {
  id: number <<PK>> <<generated>>
  name: string <<PK>>
}

entity "Restaurant" {
  id: number <<PK>> <<generated>>
  ---
  name: string
  phone: string
  address: string
  zip_code: string
  chef_name: string
  description: string
}

entity "RestaurantKitchenType" {
  restaurant_id: number <<PK>> <<FK>>
  kitchen_type_id: number <<PK>> <<FK>>
}

entity "KitchenType" {
  id: number <<PK>> <<generated>>
  name: string <<PK>>
}

entity "Menu" {
  id: number <<PK>> <<generated>>
  name: string <<PK>>
}

entity "Meal" {
  id: number <<generated>>
  menu_id: number <<FK>>
  name: string
  price: number
}

"User" ||--o{ "Order"

"Order" }o..|| "OrderStatus"
"Order" }o--|| "Restaurant"
"Order" ||--o{ "OrderEntry"
"Order" }o--|| "Employee"

"OrderEntry" ||--o{ "Meal"

"Restaurant" ||--o{ "RestaurantKitchenType"
"Restaurant" ||--|{ "Menu"

"KitchenType" ||--o{ "RestaurantKitchenType"

"Menu" ||--o{ "Meal"

"Employee" ||--|{ "EmployeePermission"
"Permission" ||..|{ "EmployeePermission"

@enduml
