@startuml

' hide the spot
hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

entity "User" {
  id: number <<PK>> <<generated>>
  --
  name: string
  phone: string
  email: string
  password_hash: string
  favourite_address: number <<FK>>
}

entity "UserAddress" {
  id: number <<PK>> <<generated>>
  --
  user_id: number <<FK>> <<index>>
  name: string
  zip_code: string
  country: string
  city: string
  street: string
  building: string
  room: string
  notes: string
}

entity "Order" {
  id: number <<PK>> <<generated>>
  --
  user_id: number <<FK>>
  address_id: number <<FK>>
  restaurant_id: number <<FK>>
  creation_date: datetime
  total_price: 	decimal(19,4)
}

entity "OrderEntry" {
  id: number <<PK>> <<generated>>
  --
  order_id: number <<FK>>
  meal_id: number <<FK>>
  price: decimal(19,4)
}

entity "OrderStatus" {
  id: number <<PK>> <<generated>>
  name: string <<PK>>
  --
}

entity "Restaurant" {
  id: number <<PK>> <<generated>>
  --
  name: string
  phone: string
  country: string
  city: string
  street: string
  building: string
  description: string
}

entity "RestaurantKitchenType" {
  restaurant_id: number <<PK>> <<FK>>
  kitchen_type_id: number <<PK>> <<FK>>
  --
}

entity "KitchenType" {
  id: number <<PK>> <<generated>>
  name: string <<PK>>
  --
}

entity "Menu" {
  id: number <<PK>> <<generated>>
  --
  restaurant_id: number <<FK>>
  name: string
}

entity "MenuMeal" {
  menu_id: number <<PK>> <<FK>>
  meal_id: number <<PK>> <<FK>>
  --
  price: decimal(19,4)
  available: boolean
}

entity "Meal" {
  id: number <<PK>> <<generated>>
  --
  menu_id: number <<FK>>
  name: string
}

"User" ||--o{ "Order"
"User" ||--o{ "UserAddress"

"Order" }o--|| "OrderStatus"
"Order" }o--|| "UserAddress"

"Order" }o--|| "Restaurant"
"Order" ||--o{ "OrderEntry"

"OrderEntry" ||--o{ "Meal"

"KitchenType" ||--o{ "RestaurantKitchenType"

"Restaurant" ||--o{ "RestaurantKitchenType"
"Restaurant" ||--|{ "Menu"

"Menu" ||--|{ "MenuMeal"
"MenuMeal" }|--|| "Meal"

@enduml
